// User Enteries
export const SUBMIT_ENTERIES_REQUEST = "SUBMIT_ENTERIES_REQUEST";
export const SUBMIT_ENTERIES_SUCCESS = "SUBMIT_ENTERIES_SUCCESS";
export const SUBMIT_ENTERIES_ERROR = "SUBMIT_ENTERIES_ERROR";

// Fetch Locations
export const GET_LOCATIONS_REQUEST = "GET_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR";

// Department
export const LOCATION_DELETE_REQUEST = "LOCATION_DELETE_REQUEST";
export const LOCATION_DELETE_SUCCESS = "LOCATION_DELETE_SUCCESS";
export const LOCATION_DELETE_ERROR = "LOCATION_DELETE_ERROR";
